config/routes.rb
Rails.application.routes.draw do

  resources :repositories
  resources :users
  

  get "/:github_user", to: "dashboard#index"

  namespace :api do
    namespace :v1 do
      get '/:github_user' => 'users#show'
      get 'repositories/:github_user' => 'repositories#index'
    end
  end

  root to: "dashboard#index"

end

app/models/repository.rb
class Repository < ActiveRecord::Base
  belongs_to :user
end

app/controllers/api/v1/repositories_controller.rb
class Api::V1::RepositoriesController < Api::V1::BaseController
  
  def index
  	user = User.where(login: params[:github_user]).first
    if user
    	repositories = user.repositories
      render(json: repositories)
    else
      render( json: "null")
    end
  end
end

app/controllers/repositories_controller.rb
class RepositoriesController < ApplicationController
  before_action :set_repository, only: [:show, :edit, :update, :destroy]

  # GET /repositories
  # GET /repositories.json
  def index
    @repositories = Repository.all
  end

  # GET /repositories/1
  # GET /repositories/1.json
  def show
  end

  # GET /repositories/new
  def new
    @repository = Repository.new
  end

  # GET /repositories/1/edit
  def edit
  end

  # POST /repositories
  # POST /repositories.json
  def create
    @repository = Repository.new(repository_params)

    respond_to do |format|
      if @repository.save
        format.html { redirect_to @repository, notice: 'Repository was successfully created.' }
        format.json { render :show, status: :created, location: @repository }
      else
        format.html { render :new }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /repositories/1
  # PATCH/PUT /repositories/1.json
  def update
    respond_to do |format|
      if @repository.update(repository_params)
        format.html { redirect_to @repository, notice: 'Repository was successfully updated.' }
        format.json { render :show, status: :ok, location: @repository }
      else
        format.html { render :edit }
        format.json { render json: @repository.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /repositories/1
  # DELETE /repositories/1.json
  def destroy
    @repository.destroy
    respond_to do |format|
      format.html { redirect_to repositories_url, notice: 'Repository was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_repository
      @repository = Repository.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def repository_params
      params.require(:repository).permit(:user_id, :name, :full_name, :description, :private, :fork, :url, :html_url, :archive_url, :assignees_url, :collaborators_url, :commits_url, :contributors_url, :forks_url, :homepage)
    end
end

app/helpers/repositories_helper.rb
module RepositoriesHelper
end

app/views/repositories/_form.html.slim
= form_for @repository do |f|
  - if @repository.errors.any?
    #error_explanation
      h2 = "#{pluralize(@repository.errors.count, "error")} prohibited this repository from being saved:"
      ul
        - @repository.errors.full_messages.each do |message|
          li = message

  .field
    = f.label :user
    = f.text_field :user
  .field
    = f.label :name
    = f.text_field :name
  .field
    = f.label :full_name
    = f.text_field :full_name
  .field
    = f.label :description
    = f.text_field :description
  .field
    = f.label :private
    = f.check_box :private
  .field
    = f.label :fork
    = f.check_box :fork
  .field
    = f.label :url
    = f.text_field :url
  .field
    = f.label :html_url
    = f.text_field :html_url
  .field
    = f.label :archive_url
    = f.text_field :archive_url
  .field
    = f.label :assignees_url
    = f.text_field :assignees_url
  .field
    = f.label :collaborators_url
    = f.text_field :collaborators_url
  .field
    = f.label :commits_url
    = f.text_field :commits_url
  .field
    = f.label :contributors_url
    = f.text_field :contributors_url
  .field
    = f.label :forks_url
    = f.text_field :forks_url
  .field
    = f.label :homepage
    = f.text_field :homepage
  .actions = f.submit

app/views/repositories/edit.html.slim
h1 Editing repository

== render 'form'

= link_to 'Show', @repository
'|
= link_to 'Back', repositories_path

app/views/repositories/index.html.slim
h1 Listing repositories

table
  thead
    tr
      th User
      th Name
      th Full name
      th Description
      th Private
      th Fork
      th Url
      th Html url
      th Archive url
      th Assignees url
      th Collaborators url
      th Commits url
      th Contributors url
      th Forks url
      th Homepage
      th
      th
      th

  tbody
    - @repositories.each do |repository|
      tr
        td = repository.user
        td = repository.name
        td = repository.full_name
        td = repository.description
        td = repository.private
        td = repository.fork
        td = repository.url
        td = repository.html_url
        td = repository.archive_url
        td = repository.assignees_url
        td = repository.collaborators_url
        td = repository.commits_url
        td = repository.contributors_url
        td = repository.forks_url
        td = repository.homepage
        td = link_to 'Show', repository
        td = link_to 'Edit', edit_repository_path(repository)
        td = link_to 'Destroy', repository, data: {:confirm => 'Are you sure?'}, :method => :delete

br

= link_to 'New Repository', new_repository_path

app/views/repositories/new.html.slim
h1 New repository

== render 'form'

= link_to 'Back', repositories_path

app/views/repositories/show.html.slim
p#notice = notice

p
  strong User:
  = @repository.user
p
  strong Name:
  = @repository.name
p
  strong Full name:
  = @repository.full_name
p
  strong Description:
  = @repository.description
p
  strong Private:
  = @repository.private
p
  strong Fork:
  = @repository.fork
p
  strong Url:
  = @repository.url
p
  strong Html url:
  = @repository.html_url
p
  strong Archive url:
  = @repository.archive_url
p
  strong Assignees url:
  = @repository.assignees_url
p
  strong Collaborators url:
  = @repository.collaborators_url
p
  strong Commits url:
  = @repository.commits_url
p
  strong Contributors url:
  = @repository.contributors_url
p
  strong Forks url:
  = @repository.forks_url
p
  strong Homepage:
  = @repository.homepage

= link_to 'Edit', edit_repository_path(@repository)
'|
= link_to 'Back', repositories_path